// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:1b9e3522-6eae-4814-b764-c50b8350c5e5',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'kayuaccesorios-hosting-mobilehub-1402282288',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1yzff9pvayv4p.cloudfront.net',
    'aws_mobile_analytics_app_id': '3001e1eb666644e8900c577032b10254',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'e7fb96de-a7e0-4b5d-b496-aef19320e544',
    'aws_project_name': 'Kayuaccesorios',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'kayuaccesorios-mobilehub-1402282288',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_ldFXhoDz3',
    'aws_user_pools_mfa_type': 'OPTIONAL',
    'aws_user_pools_web_client_id': '5eggfqg03foml29s0s11j5fns9',
}

export default awsmobile;
